name: tests

trigger: ['*']
pr: ['*']

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: run_test
    strategy:
      matrix:
        node_22:
          node.version: '22.x'

    timeoutInMinutes: 15

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node.version)
        displayName: 'Install Node.js'

      - checkout: self
        displayName: Checkout assemblyline-ui-frontend

      - script: |
          npm install -g pnpm
        displayName: 'Install PNPM'

      - script: |
          # Try to checkout the matching branch, if the command fails, don't care.
          export BRANCH_NAME=$(basename -- "$SYSTEM_PULLREQUEST_SOURCEBRANCH")
          export BRANCH_NAME=${BRANCH_NAME:-"$BUILD_SOURCEBRANCHNAME"}
          git checkout -b $BRANCH_NAME -t origin/$BRANCH_NAME || true

          pnpm install
        displayName: Install assemblyline-ui-frontend

      - script: |
          set -xv  # Echo commands before they are run
          pnpm run tsc
        displayName: TypeScript

      - script: |
          set -xv  # Echo commands before they are run
          pnpm run ci-test
        displayName: Test

      - script: |
          set -xv  # Echo commands before they are run
          pnpm run ci-lint
        displayName: ESLint

      - task: PublishCodeCoverageResults@2
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml
